### ISSUE TITLE
Crafting sticks only give 2 sticks instead of 4

### ISSUE THREAD

**Issue by santastolle** [pnk2u/More-Stick-Variants#2]
v1.0.3
MC v1.21

When you craft sticks in vanilla you get 4 sticks, but with this mod you only get 2.

**Comment by pnk2u** [comment]
Oh, my god, how did I think it was two... Thanks for the report as usual and thank you for your patience here especially. @-@
Fixed in version 1.0.4.

**Comment by santastolle** [comment]
I feel you, I had to double check. Thank you for the great work and for the laugh! :)
