### ISSUE TITLE
can not craft wooden tools using the wooden stick variants

### ISSUE THREAD

**Issue by geyesborg** [pnk2u/More-Stick-Variants#3]
I am on minecraft 1,21,1 on the latest neoforge

**Comment by pnk2u** [comment]
Uhm, this is a Fabric mod. Unfortunately, I cannot help you with things related to running this mod on Neoforge.

**Comment by geyesborg** [comment]
So your saying it works as intended on fabric.

**Comment by pnk2u** [comment]
That's correct - I tested it, just to make sure, in response to this issue. The only reason why it wouldn't work on Fabric would be another mod/datapack changing the affected recipes.

**Comment by geyesborg** [comment]
Ok thank you for the response. Do you have any plans to port to neoforge?

**Comment by pnk2u** [comment]
I'm sorry, no, not at this time. But if I ever do port it to another mod loader it would be Neoforge, so it's not unlikely it will happen at some point.

**Comment by MSVaah** [comment]
I'm also having a similar issue with this, on Fabric 1.20.1. After looking over the code, it seems that spruce sticks is missing from the sticks and stick_variants tags, and as such can't be used to craft anything outside of recipes from the other More (Torches, Armor Stands Stands, etc,.) mods.

**Comment by pnk2u** [comment]
@MSVaah Thanks for looking into it, that was really helpful. And @geyesborg , thanks for reporting this issue in the first place and sorry for misjudging its cause/nature at first.
The issue has been fixed in version 1.1.1.

**Comment by geyesborg** [comment]
Yea no problem.
